#!/bin/bash

if [ $# -lt 5 ]; then
	echo "Usage: $0 GOGS_PROJECT GOGS_USER GOGS_PASSWORD PROJECT_PREFIX DOMAIN_NAME"
	exit 1
fi

set -e

PROJECTNAME=$1
GOGSUSER=$2
GOGSPASSWORD=$3
PROJECT_PREFIX=$4
DOMAIN_NAME=$5

GOGS_ROUTE_NAME="$(oc get routes --no-headers  -o custom-columns=Name:metadata.name -n $PROJECTNAME | grep gogs)"
if [ -z "${GOGS_ROUTE_NAME}" ]; then
    echo "Gogs route name is not valid - name: ${GOGS_ROUTE_NAME}"
    exit 1
fi

GOGS_HOSTNAME="$(oc get route ${GOGS_ROUTE_NAME} --no-headers  -o custom-columns=domain:spec.host  -n $PROJECTNAME)"
echo "Gogs Hostname: ${GOGS_HOSTNAME}"
if [ -z "${GOGS_HOSTNAME}" ]; then
    echo "Gogs hostname is not valid"
    exit 1
fi


echo "Cloning sample source code from github..."
git clone --bare https://github.com/chengkuangan/nationalparks.git

cd nationalparks.git

echo "Creating gogs token..."
curl -v  -X POST -H "Content-Type: application/json" -d '{"name":"sample-token","sha1":"8a4fc41b4868aecdd623b10cb1b64a36c6ee51f3"}' http://${GOGSUSER}:${GOGSPASSWORD}@${GOGS_HOSTNAME}/api/v1/users/${GOGSUSER}/tokens

echo "Creating repository..."
curl -H "Content-Type: application/json" -d '{"name": "nationalparks", "description": "National Parks Source Codes", "private": false}' -X POST http://${GOGSUSER}:${GOGSPASSWORD}@${GOGS_HOSTNAME}/api/v1/user/repos?token=8a4fc41b4868aecdd623b10cb1b64a36c6ee51f3

echo "Push bare code as mirror to gogs..."
git push --mirror http://${GOGSUSER}:${GOGSPASSWORD}@${GOGS_HOSTNAME}/${GOGSUSER}/nationalparks.git

cd ..
rm -rf nationalparks.git

echo "Clone the git repo on gogs to modify the Jenkinsfile ..."
git clone http://${GOGS_HOSTNAME}/${GOGSUSER}/nationalparks.git 
cd nationalparks
sed -i -e "s/def projectNamePrefix = \"\"/def projectNamePrefix = \"${PROJECT_PREFIX}\"/g" ./Jenkinsfile
sed -i -e "s/def wildcardDNS = \".ocp.demo.com\"/def wildcardDNS = \".${DOMAIN_NAME}\"/g" ./Jenkinsfile
echo "Push bare codes as mirror to gogs ..."
git add .
git commit -m "Updated Jenkinsfile"
git push http://${GOGSUSER}:${GOGSPASSWORD}@${GOGS_HOSTNAME}/${GOGSUSER}/nationalparks.git 
cd ..
rm -rf nationalparks