#!/bin/bash

# Check if we're running in RHPDS.
#
if [[ "${HOSTNAME}" != "bastion."* ]]; then
  echo "we are not running in RHPDS"
  exit 1
fi

if [[ "${HOSTNAME}" != *".openshiftworkshop.com" ]]; then
  echo "we are not running in RHPDS"
  exit 1
fi

CITYGUID=$(echo $HOSTNAME | sed -e 's/bastion.\([^.]*\).openshiftworkshop.com/\1/')
if [ -n "$CITYGUID" ]; then
  echo "https://master.${CITYGUID}.openshiftworkshop.com"
  exit 0
fi

echo "we are not running in RHPDS"
exit 1
