#!/bin/bash

if [ $# -lt 1 ]; then
	echo "Usage: $0 NEXUS_PROJECT"
	exit 1
fi

PROJECTNAME=$1

NEXUS_POD_READY="false"

echo "Checking if nexus POD is ready..."

NEXUS_POD_NAME="$(oc get pods --no-headers -o custom-columns=NAME:.metadata.name -n $PROJECTNAME | grep nexus3 )"
while [ "$NEXUS_POD_READY" = "false" ]
do
   sleep 5
   GOGS_POD_READY="$(oc get pod ${NEXUS_POD_NAME} -o custom-columns=Ready:status.containerStatuses[0].ready --no-headers -n $PROJECTNAME)"
   echo "POD: $NEXUS_POD_NAME, ready: $NEXUS_POD_READY ..."
done