#!/bin/bash

if [ $# -lt 1 ]; then
	echo "Usage: $0 GOGS_PROJECT"
	exit 1
fi

PROJECTNAME=$1

GOGS_POD_READY="false"

echo "Checking if gogs POD is ready..."

GOGS_POD_NAME="$(oc get pods --no-headers -o custom-columns=NAME:.metadata.name -n $PROJECTNAME | grep gogs-[^postgresql] )"
while [ "$GOGS_POD_READY" = "false" ]
do
   sleep 5
   GOGS_POD_READY="$(oc get pod ${GOGS_POD_NAME} -o custom-columns=Ready:status.containerStatuses[0].ready --no-headers -n $PROJECTNAME)"
   echo "POD: $GOGS_POD_NAME, ready: $GOGS_POD_READY ..."
done