#!/bin/bash

if [ $# -lt 2 ]; then
  echo "Usage: $0 PROJECT ROUTENAME"
  exit 1
fi

PROJECT=$1
ROUTENAME=$2

ROUTE=$(oc get route/${ROUTENAME} -n ${PROJECT} --template='{{.spec.host}}' 2> /dev/null)
if [ -z "$ROUTE" ]; then
  echo "Route $ROUTENAME does not exist in project $PROJECT"
  exit 1
fi

SCHEME="http"
if [ "$(oc get route/${ROUTENAME} -n ${PROJECT} --template='{{.spec.tls}}' 2> /dev/null)" != "<no value>" ]; then
  SCHEME="https"
fi

ROUTE="${SCHEME}://${ROUTE}"
echo -n "Waiting for ${ROUTE} to come up..."
RC=0
while [ $RC -ne 200 -a $RC -ne 302 -a $RC -ne 403 ]; do
  sleep 5
  RC=$(curl -k -sL -w "%{http_code}" ${ROUTE} -o /dev/null)
  echo -n "."
done

echo "done"